# -*- coding: utf-8 -*-
"""音視訊迴路盒查詢網頁

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qs92fxnHH6TUu7Dusmk07AjNdDsthmr2
"""

import streamlit as st
import pandas as pd

# 網頁基本設定：設置標題與佈局
st.set_page_config(
    page_title="AV 迴路盒查詢系統",
    page_icon="🔍",
    layout="wide"
)

# 套用自定義 CSS 提升質感
st.markdown("""
    <style>
    .main {
        background-color: #f8f9fa;
    }
    .stMetric {
        background-color: #ffffff;
        padding: 15px;
        border-radius: 10px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.05);
    }
    </style>
    """, unsafe_allow_stdio=True)

# 定義讀取資料的函數，並使用快取避免重複讀取
@st.cache_data
def load_data():
    # 讀取您上傳的 CSV 檔案
    # 注意：檔案名稱必須與 GitHub 上的檔案名稱完全一致
    file_path = "Cable list  音視訊 20201109.xlsx - 迴路盒.csv"
    try:
        df = pd.read_csv(file_path)
        # 資料預處理：統一搜尋格式（大寫、移除空格、移除橫線）
        df['search_id'] = df['迴路盒編號'].astype(str).str.upper().str.replace(' ', '').str.replace('-', '')
        return df
    except Exception as e:
        st.error(f"無法讀取資料檔案，請確認檔名是否正確。錯誤訊息: {e}")
        return None

# 執行讀取資料
df = load_data()

# 標題區
st.title("📟 音視訊迴路盒快速查詢系統")
st.markdown("---")

if df is not None:
    # 建立搜尋列
    st.subheader("請輸入迴路盒編號")
    user_input = st.text_input("搜尋範例：AV 04-01 或直接輸入 04-01", placeholder="例如: 04-01")

    if user_input:
        # 處理使用者輸入的關鍵字
        query = user_input.upper().replace(' ', '').replace('-', '')
        if not query.startswith("AV"):
            query = "AV" + query

        # 在資料庫中比對
        match = df[df['search_id'] == query]

        if not match.empty:
            # 取得該盒子的一般資訊（取第一筆作為代表）
            info = match.iloc[0]

            # 使用兩欄佈局顯示重要位置資訊
            col1, col2 = st.columns(2)
            with col1:
                st.metric("所屬廳別", info['廳別'].split('\n')[0])
            with col2:
                st.metric("位置詳細", info['迴路盒位置'].replace('\n', ' '))

            st.markdown("---")

            # 顯示接口統計摘要
            st.subheader("📦 接口數量匯總")
            # 依照系統、接頭、接頭型式進行分組加總
            summary = match.groupby(['系統', '接頭', '接頭型式'])['接頭數'].sum().reset_index()
            summary.columns = ['系統類型', '接頭型號', '安裝/型式', '總數量']
            st.dataframe(summary, use_container_width=True, hide_index=True)

            # 顯示詳細線路清單
            with st.expander("🔍 點擊展開：查看每一條線路的標示號碼與目的地"):
                detailed_df = match[['迴路標示號碼', '線材', '目的地樓層', '機房名稱', '機櫃', '點位']].copy()
                detailed_df.columns = ['迴路標示', '線材型號', '目的地樓層', '機房名稱', '機櫃編號', '點位']
                st.write(detailed_df)
        else:
            st.warning(f"找不到編號「{user_input}」的相關資料，請檢查編號是否有誤。")
    else:
        # 未輸入時的提示畫面
        st.info("💡 提示：輸入 4F 的編號（如 04-01）可快速查看舞台右側的設備狀況。")

        # 顯示最近的搜尋建議 (選配)
        st.markdown("### 快速連結")
        quick_cols = st.columns(4)
        sample_ids = ["AV 04-01", "AV 04-02", "AV 04-03", "AV 04-04"]
        for i, sid in enumerate(sample_ids):
            if quick_cols[i].button(sid):
                st.info(f"請在搜尋框輸入 {sid} 進行查詢")

# 頁尾資訊
st.markdown("---")
st.caption("資料來源：Cable list 音視訊 20201109 | 系統最後更新：2026-01-06")
